{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-csr
  labels:
{{ include "teleport.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  - certificatesigningrequests/status
  verbs:
  - update
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-teleport-admin-role
  labels:
{{ include "teleport.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - jobs
  - services
  - statefulsets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-csr
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-csr
subjects:
- kind: ServiceAccount
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
  namespace: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-teleport-admin-role
  namespace: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-teleport-admin-role
subjects:
- kind: Group
  name: teleport-users

{{- if not (eq (index .Values.extraClusterNames 0) "") -}}
{{- $root := . -}}
{{- range .Values.extraClusterNames }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "teleport.fullname" $root }}-{{.}}-csr
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "teleport.fullname" $root }}-{{ $root.Values.mainClusterName }}-csr
subjects:
- kind: ServiceAccount
  name: {{ template "teleport.fullname" $root }}-{{.}}
  namespace: {{ template "teleport.fullname" $root }}-{{.}}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "teleport.fullname" $root }}-{{.}}-teleport-admin-role
  namespace: {{ template "teleport.fullname" $root }}-{{.}}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "teleport.fullname" $root }}-{{ $root.Values.mainClusterName }}-teleport-admin-role
subjects:
- kind: Group
  name: teleport-users
{{- end -}}
{{- end -}}
{{- end }}